### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ianmiell** [rodricios/eatiht#18] opened 2015-04-04 10:53 UTC
imiell@osboxes:~$ eatiht http://news.yahoo.com/curiosity-rover-drills-mars-rock-finds-water-122321635.html
: No such file or directory

**Comment by rodricios** [comment] 2015-04-04 18:36
Hi @ianmiell, I can't seem to reproduce your problem. What version are you running? Which branch?

**Comment by eugene-eeo** [comment] 2015-04-05 00:32
@ianmiell I think it's a problem with the shell... It doesn't look like a Python exception/error to me. Perhaps try quoting the URL with single quotes?

**Comment by rodricios** [comment] 2015-04-06 07:19
Well, I'm going to close this one. I'm hoping it's a just a console error. It can possibly be related to the script installation setting within setup.py, but I doubt it.

**Closed by rodricios** 2015-04-06 07:19 UTC

**Comment by thallada** [comment] 2015-10-28 05:25
I was having this issue (on a linux system) and switching the eatiht executable from windows line endings to unix line endings fixed the problem. I think it's because the shell get's confused with trying to parse the shebang with the carriage return and line feed on the end.

**Comment by ianmiell** [comment] 2015-10-28 09:37
```imiell@Ians-Air:/space/git/work/pass$ pip install eatiht

You are using pip version 7.1.0, however version 7.1.2 is available.

You should consider upgrading via the 'pip install --upgrade pip' command.

Collecting eatiht

  Downloading eatiht-0.1.14.zip (137kB)

    100% |████████████████████████████████| 139kB 2.3MB/s

Collecting lxml (from eatiht)

  Downloading lxml-3.4.4.tar.gz (3.5MB)

    100% |████████████████████████████████| 3.5MB 96kB/s

Collecting chardet (from eatiht)

  Downloading chardet-2.3.0.tar.gz (164kB)

    100% |████████████████████████████████| 167kB 1.7MB/s

Building wheels for collected packages: eatiht, lxml, chardet

  Running setup.py bdist_wheel for eatiht

  Stored in directory:
/Users/imiell/Library/Caches/pip/wheels/d2/24/df/42e047d4c1bfe8ff061580c895f6652f3eaa2722ff2ef02651

  Running setup.py bdist_wheel for lxml

  Stored in directory:
/Users/imiell/Library/Caches/pip/wheels/62/29/26/11383932dbed36e9fe68552fc755a96cfc6fa5833d948620da

  Running setup.py bdist_wheel for chardet

  Stored in directory:
/Users/imiell/Library/Caches/pip/wheels/a4/24/b6/124a2516812185506f0573d4abbeb7d08596f53618f8cc960d

Successfully built eatiht lxml chardet

Installing collected packages: lxml, chardet, eatiht

Successfully installed chardet-2.3.0 eatiht-0.1.14 lxml-3.4.4

imiell@Ians-Air:/space/git/work/pass$ eatiht
http://news.yahoo.com/curiosity-rover-drills-mars-rock-finds-water-122321635.html

env: python\r: No such file or directory```

On Wed, Oct 28, 2015 at 5:25 AM, Tyler Hallada <notifications@github.com>
wrote:

> I was having this issue (on a linux system) and switching the eatiht
> executable from windows line endings to unix line endings fixed the
> problem. I think it's because the shell get's confused with trying to parse
> the shebang with the carriage return and line feed on the end.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodricios/eatiht/issues/18#issuecomment-151728511>.
>



-- 
Currently co-authoring a book on Docker: Get 39% off with the code 39miell
<http://manning.com/miell/?a_aid=zwischenzugs&a_bid=e0d48f62>

**Comment by rodricios** [comment] 2015-10-29 06:19
Thanks for bringing this to my attention. Will look into it as time permits.
